services:
  - type: web
    name: app-danza
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: "./start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:wF0W2AawI8xXBpEoK4voJO0DC5CbRdyjHd0Y9D89E4I=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: jqFAcoyneouHdTbQjipyXOGyIDkiVZMt
      - key: ASSET_URL
        value: https://app-danza.onrender.com
