services:
  - type: web
    name: danza-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://danza-app.onrender.com

  - type: pserv
    name: php
    env: docker
    dockerfilePath: ./Dockerfile.php
