services:
  - type: web
    name: danza-laravel
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: shortline.proxy.rlwy.net
      - key: DB_PORT
        value: 26279
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: jqFAcoyneouHdTbQjipyXOGyIDkiVZMt
