services:
  - type: pserv
    name: php
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://danza-app.onrender.com
    dependsOn:
      - php
